trigger:
  branches:
    include:
      - master
      - '*-dev'
  tags:
    include:
      - v*

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  system.debug: false
  isTag: 'false'
  isSnapshot: 'false'

jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          curl 'https://cdn.azul.com/zulu/bin/zulu18.28.13-ca-jdk18.0.0-linux_x64.tar.gz' --output $(Agent.TempDirectory)/jdk-latest-linux_x64.tar.gz

      - task: JavaToolInstaller@0
        inputs:
          versionSpec: "18"
          jdkArchitectureOption: x64
          jdkSourceOption: LocalDirectory
          jdkFile: $(Agent.TempDirectory)/jdk-latest-linux_x64.tar.gz
          jdkDestinationDirectory: $(Agent.ToolsDirectory)/binaries/openjdk
          cleanDestinationDirectory: true

      - bash: |
          echo '##vso[task.setvariable variable=isTag;]true'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

      - bash: |
          echo '##vso[task.setvariable variable=isSnapshot;]true'
        condition: and(succeeded(), endsWith(variables['Build.SourceBranch'], '-SNAPSHOT'))

      - task: Gradle@2
        env:
          IS_TAG: $(isTag)
          REPO_TAG_NAME: $(Build.SourceBranchName)
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'jar'

      - task: GithubRelease@0
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
        inputs:
          gitHubConnection: binjr-bot
          repositoryName: fthevenet/binjr-adapter-elitebgs
          action: edit
          tag: $(Build.SourceBranchName)
          assets: |
            $(System.DefaultWorkingDirectory)/build/libs/*.jar
          assetUploadMode: 'replace'
          releaseNotesSource: 'file'
          releaseNotesFile: $(System.DefaultWorkingDirectory)/UNRELEASED.md
          addChangeLog: false
          isPreRelease: $(isSnapshot)