/*
 *    Copyright 2021 Frederic Thevenet
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * Elite BGS API
 * An API for Elite BGS
 *
 * OpenAPI spec version: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package eu.fthevenet.binjr.sources.adapters.elitebgs.api.v5;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * EBGSSystemHistoryV5
 */


public class EBGSSystemHistoryV5 {
  @SerializedName("_id")
  private String _id;

  @SerializedName("updated_at")
  private String updatedAt;

  @SerializedName("updated_by")
  private String updatedBy;

  @SerializedName("population")
  private long population;

  @SerializedName("government")
  private String government;

  @SerializedName("allegiance")
  private String allegiance;

  @SerializedName("state")
  private String state;

  @SerializedName("security")
  private String security;

  @SerializedName("controlling_minor_faction_cased")
  private String controllingMinorFactionCased;

  @SerializedName("controlling_minor_faction")
  private String controllingMinorFaction;

  @SerializedName("controlling_minor_faction_id")
  private String controllingMinorFactionId;

  @SerializedName("factions")
  private List<EBGSFactionRefV5> factions;

  @SerializedName("conflicts")
  private List<EBGSConflictSystemV5> conflicts;

  public EBGSSystemHistoryV5 _id(String _id) {
    this._id = _id;
    return this;
  }

   /**
   * Get _id
   * @return _id
  **/

  public String getId() {
    return _id;
  }

  public void setId(String _id) {
    this._id = _id;
  }

  public EBGSSystemHistoryV5 updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/

  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public EBGSSystemHistoryV5 updatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Get updatedBy
   * @return updatedBy
  **/

  public String getUpdatedBy() {
    return updatedBy;
  }

  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }

  public EBGSSystemHistoryV5 population(long population) {
    this.population = population;
    return this;
  }

   /**
   * Get population
   * @return population
  **/

  public long getPopulation() {
    return population;
  }

  public void setPopulation(long population) {
    this.population = population;
  }

  public EBGSSystemHistoryV5 government(String government) {
    this.government = government;
    return this;
  }

   /**
   * Get government
   * @return government
  **/

  public String getGovernment() {
    return government;
  }

  public void setGovernment(String government) {
    this.government = government;
  }

  public EBGSSystemHistoryV5 allegiance(String allegiance) {
    this.allegiance = allegiance;
    return this;
  }

   /**
   * Get allegiance
   * @return allegiance
  **/

  public String getAllegiance() {
    return allegiance;
  }

  public void setAllegiance(String allegiance) {
    this.allegiance = allegiance;
  }

  public EBGSSystemHistoryV5 state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/

  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public EBGSSystemHistoryV5 security(String security) {
    this.security = security;
    return this;
  }

   /**
   * Get security
   * @return security
  **/

  public String getSecurity() {
    return security;
  }

  public void setSecurity(String security) {
    this.security = security;
  }

  public EBGSSystemHistoryV5 controllingMinorFactionCased(String controllingMinorFactionCased) {
    this.controllingMinorFactionCased = controllingMinorFactionCased;
    return this;
  }

   /**
   * Get controllingMinorFactionCased
   * @return controllingMinorFactionCased
  **/

  public String getControllingMinorFactionCased() {
    return controllingMinorFactionCased;
  }

  public void setControllingMinorFactionCased(String controllingMinorFactionCased) {
    this.controllingMinorFactionCased = controllingMinorFactionCased;
  }

  public EBGSSystemHistoryV5 controllingMinorFaction(String controllingMinorFaction) {
    this.controllingMinorFaction = controllingMinorFaction;
    return this;
  }

   /**
   * Get controllingMinorFaction
   * @return controllingMinorFaction
  **/

  public String getControllingMinorFaction() {
    return controllingMinorFaction;
  }

  public void setControllingMinorFaction(String controllingMinorFaction) {
    this.controllingMinorFaction = controllingMinorFaction;
  }

  public EBGSSystemHistoryV5 controllingMinorFactionId(String controllingMinorFactionId) {
    this.controllingMinorFactionId = controllingMinorFactionId;
    return this;
  }

   /**
   * Get controllingMinorFactionId
   * @return controllingMinorFactionId
  **/

  public String getControllingMinorFactionId() {
    return controllingMinorFactionId;
  }

  public void setControllingMinorFactionId(String controllingMinorFactionId) {
    this.controllingMinorFactionId = controllingMinorFactionId;
  }

  public EBGSSystemHistoryV5 factions(List<EBGSFactionRefV5> factions) {
    this.factions = factions;
    return this;
  }

  public EBGSSystemHistoryV5 addFactionsItem(EBGSFactionRefV5 factionsItem) {
    if (this.factions == null) {
      this.factions = new ArrayList<EBGSFactionRefV5>();
    }
    this.factions.add(factionsItem);
    return this;
  }

   /**
   * Get factions
   * @return factions
  **/

  public List<EBGSFactionRefV5> getFactions() {
    return factions;
  }

  public void setFactions(List<EBGSFactionRefV5> factions) {
    this.factions = factions;
  }

  public EBGSSystemHistoryV5 conflicts(List<EBGSConflictSystemV5> conflicts) {
    this.conflicts = conflicts;
    return this;
  }

  public EBGSSystemHistoryV5 addConflictsItem(EBGSConflictSystemV5 conflictsItem) {
    if (this.conflicts == null) {
      this.conflicts = new ArrayList<EBGSConflictSystemV5>();
    }
    this.conflicts.add(conflictsItem);
    return this;
  }

   /**
   * Get conflicts
   * @return conflicts
  **/

  public List<EBGSConflictSystemV5> getConflicts() {
    return conflicts;
  }

  public void setConflicts(List<EBGSConflictSystemV5> conflicts) {
    this.conflicts = conflicts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EBGSSystemHistoryV5 ebGSSystemHistoryV5 = (EBGSSystemHistoryV5) o;
    return Objects.equals(this._id, ebGSSystemHistoryV5._id) &&
        Objects.equals(this.updatedAt, ebGSSystemHistoryV5.updatedAt) &&
        Objects.equals(this.updatedBy, ebGSSystemHistoryV5.updatedBy) &&
        Objects.equals(this.population, ebGSSystemHistoryV5.population) &&
        Objects.equals(this.government, ebGSSystemHistoryV5.government) &&
        Objects.equals(this.allegiance, ebGSSystemHistoryV5.allegiance) &&
        Objects.equals(this.state, ebGSSystemHistoryV5.state) &&
        Objects.equals(this.security, ebGSSystemHistoryV5.security) &&
        Objects.equals(this.controllingMinorFactionCased, ebGSSystemHistoryV5.controllingMinorFactionCased) &&
        Objects.equals(this.controllingMinorFaction, ebGSSystemHistoryV5.controllingMinorFaction) &&
        Objects.equals(this.controllingMinorFactionId, ebGSSystemHistoryV5.controllingMinorFactionId) &&
        Objects.equals(this.factions, ebGSSystemHistoryV5.factions) &&
        Objects.equals(this.conflicts, ebGSSystemHistoryV5.conflicts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, updatedAt, updatedBy, population, government, allegiance, state, security, controllingMinorFactionCased, controllingMinorFaction, controllingMinorFactionId, factions, conflicts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EBGSSystemHistoryV5 {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    population: ").append(toIndentedString(population)).append("\n");
    sb.append("    government: ").append(toIndentedString(government)).append("\n");
    sb.append("    allegiance: ").append(toIndentedString(allegiance)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    security: ").append(toIndentedString(security)).append("\n");
    sb.append("    controllingMinorFactionCased: ").append(toIndentedString(controllingMinorFactionCased)).append("\n");
    sb.append("    controllingMinorFaction: ").append(toIndentedString(controllingMinorFaction)).append("\n");
    sb.append("    controllingMinorFactionId: ").append(toIndentedString(controllingMinorFactionId)).append("\n");
    sb.append("    factions: ").append(toIndentedString(factions)).append("\n");
    sb.append("    conflicts: ").append(toIndentedString(conflicts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
