/*
 *    Copyright 2021 Frederic Thevenet
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * Elite BGS API
 * An API for Elite BGS
 *
 * OpenAPI spec version: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package eu.fthevenet.binjr.sources.adapters.elitebgs.api.v5;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * EBGSSystemsV5
 */


public class EBGSSystemsV5 {
  @SerializedName("_id")
  private String _id;

  @SerializedName("__v")
  private int _v;

  @SerializedName("eddb_id")
  private int eddbId;

  @SerializedName("name")
  private String name;

  @SerializedName("name_lower")
  private String nameLower;

  @SerializedName("name_aliases")
  private List<EBGSNameAliasV5> nameAliases;

  @SerializedName("x")
  private double x ;

  @SerializedName("y")
  private double y ;

  @SerializedName("z")
  private double z;

  @SerializedName("system_address")
  private String systemAddress;

  @SerializedName("population")
  private long population;

  @SerializedName("government")
  private String government;

  @SerializedName("allegiance")
  private String allegiance;

  @SerializedName("state")
  private String state;

  @SerializedName("security")
  private String security;

  @SerializedName("primary_economy")
  private String primaryEconomy;

  @SerializedName("secondary_economy")
  private String secondaryEconomy;

  @SerializedName("needs_permit")
  private boolean needsPermit;

  @SerializedName("reserve_type")
  private String reserveType;

  @SerializedName("controlling_minor_faction_cased")
  private String controllingMinorFactionCased;

  @SerializedName("controlling_minor_faction")
  private String controllingMinorFaction;

  @SerializedName("controlling_minor_faction_id")
  private String controllingMinorFactionId;

  @SerializedName("factions")
  private List<EBGSFactionRefV5> factions;

  @SerializedName("conflicts")
  private List<EBGSConflictSystemV5> conflicts;

  @SerializedName("faction_history")
  private List<EBGSFactionHistorySystemV5> factionHistory;

  @SerializedName("history")
  private List<EBGSSystemHistoryV5> history;

  @SerializedName("updated_at")
  private String updatedAt;

  public EBGSSystemsV5 _id(String _id) {
    this._id = _id;
    return this;
  }

   /**
   * Get _id
   * @return _id
  **/

  public String getId() {
    return _id;
  }

  public void setId(String _id) {
    this._id = _id;
  }

  public EBGSSystemsV5 _v(int _v) {
    this._v = _v;
    return this;
  }

   /**
   * Get _v
   * @return _v
  **/

  public int getV() {
    return _v;
  }

  public void setV(int _v) {
    this._v = _v;
  }

  public EBGSSystemsV5 eddbId(int eddbId) {
    this.eddbId = eddbId;
    return this;
  }

   /**
   * Get eddbId
   * @return eddbId
  **/

  public int getEddbId() {
    return eddbId;
  }

  public void setEddbId(int eddbId) {
    this.eddbId = eddbId;
  }

  public EBGSSystemsV5 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EBGSSystemsV5 nameLower(String nameLower) {
    this.nameLower = nameLower;
    return this;
  }

   /**
   * Get nameLower
   * @return nameLower
  **/

  public String getNameLower() {
    return nameLower;
  }

  public void setNameLower(String nameLower) {
    this.nameLower = nameLower;
  }

  public EBGSSystemsV5 nameAliases(List<EBGSNameAliasV5> nameAliases) {
    this.nameAliases = nameAliases;
    return this;
  }

  public EBGSSystemsV5 addNameAliasesItem(EBGSNameAliasV5 nameAliasesItem) {
    if (this.nameAliases == null) {
      this.nameAliases = new ArrayList<EBGSNameAliasV5>();
    }
    this.nameAliases.add(nameAliasesItem);
    return this;
  }

   /**
   * Get nameAliases
   * @return nameAliases
  **/

  public List<EBGSNameAliasV5> getNameAliases() {
    return nameAliases;
  }

  public void setNameAliases(List<EBGSNameAliasV5> nameAliases) {
    this.nameAliases = nameAliases;
  }

  public EBGSSystemsV5 x(Double x) {
    this.x = x;
    return this;
  }

   /**
   * Get x
   * @return x
  **/

  public Double getX() {
    return x;
  }

  public void setX(Double x) {
    this.x = x;
  }

  public EBGSSystemsV5 y(Double y) {
    this.y = y;
    return this;
  }

   /**
   * Get y
   * @return y
  **/

  public Double getY() {
    return y;
  }

  public void setY(Double y) {
    this.y = y;
  }

  public EBGSSystemsV5 z(Double z) {
    this.z = z;
    return this;
  }

   /**
   * Get z
   * @return z
  **/

  public Double getZ() {
    return z;
  }

  public void setZ(Double z) {
    this.z = z;
  }

  public EBGSSystemsV5 systemAddress(String systemAddress) {
    this.systemAddress = systemAddress;
    return this;
  }

   /**
   * Get systemAddress
   * @return systemAddress
  **/

  public String getSystemAddress() {
    return systemAddress;
  }

  public void setSystemAddress(String systemAddress) {
    this.systemAddress = systemAddress;
  }

  public EBGSSystemsV5 population(long population) {
    this.population = population;
    return this;
  }

   /**
   * Get population
   * @return population
  **/

  public long getPopulation() {
    return population;
  }

  public void setPopulation(long population) {
    this.population = population;
  }

  public EBGSSystemsV5 government(String government) {
    this.government = government;
    return this;
  }

   /**
   * Get government
   * @return government
  **/

  public String getGovernment() {
    return government;
  }

  public void setGovernment(String government) {
    this.government = government;
  }

  public EBGSSystemsV5 allegiance(String allegiance) {
    this.allegiance = allegiance;
    return this;
  }

   /**
   * Get allegiance
   * @return allegiance
  **/

  public String getAllegiance() {
    return allegiance;
  }

  public void setAllegiance(String allegiance) {
    this.allegiance = allegiance;
  }

  public EBGSSystemsV5 state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/

  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public EBGSSystemsV5 security(String security) {
    this.security = security;
    return this;
  }

   /**
   * Get security
   * @return security
  **/

  public String getSecurity() {
    return security;
  }

  public void setSecurity(String security) {
    this.security = security;
  }

  public EBGSSystemsV5 primaryEconomy(String primaryEconomy) {
    this.primaryEconomy = primaryEconomy;
    return this;
  }

   /**
   * Get primaryEconomy
   * @return primaryEconomy
  **/

  public String getPrimaryEconomy() {
    return primaryEconomy;
  }

  public void setPrimaryEconomy(String primaryEconomy) {
    this.primaryEconomy = primaryEconomy;
  }

  public EBGSSystemsV5 secondaryEconomy(String secondaryEconomy) {
    this.secondaryEconomy = secondaryEconomy;
    return this;
  }

   /**
   * Get secondaryEconomy
   * @return secondaryEconomy
  **/

  public String getSecondaryEconomy() {
    return secondaryEconomy;
  }

  public void setSecondaryEconomy(String secondaryEconomy) {
    this.secondaryEconomy = secondaryEconomy;
  }

  public EBGSSystemsV5 needsPermit(boolean needsPermit) {
    this.needsPermit = needsPermit;
    return this;
  }

   /**
   * Get needsPermit
   * @return needsPermit
  **/

  public boolean isNeedsPermit() {
    return needsPermit;
  }

  public void setNeedsPermit(boolean needsPermit) {
    this.needsPermit = needsPermit;
  }

  public EBGSSystemsV5 reserveType(String reserveType) {
    this.reserveType = reserveType;
    return this;
  }

   /**
   * Get reserveType
   * @return reserveType
  **/

  public String getReserveType() {
    return reserveType;
  }

  public void setReserveType(String reserveType) {
    this.reserveType = reserveType;
  }

  public EBGSSystemsV5 controllingMinorFactionCased(String controllingMinorFactionCased) {
    this.controllingMinorFactionCased = controllingMinorFactionCased;
    return this;
  }

   /**
   * Get controllingMinorFactionCased
   * @return controllingMinorFactionCased
  **/

  public String getControllingMinorFactionCased() {
    return controllingMinorFactionCased;
  }

  public void setControllingMinorFactionCased(String controllingMinorFactionCased) {
    this.controllingMinorFactionCased = controllingMinorFactionCased;
  }

  public EBGSSystemsV5 controllingMinorFaction(String controllingMinorFaction) {
    this.controllingMinorFaction = controllingMinorFaction;
    return this;
  }

   /**
   * Get controllingMinorFaction
   * @return controllingMinorFaction
  **/

  public String getControllingMinorFaction() {
    return controllingMinorFaction;
  }

  public void setControllingMinorFaction(String controllingMinorFaction) {
    this.controllingMinorFaction = controllingMinorFaction;
  }

  public EBGSSystemsV5 controllingMinorFactionId(String controllingMinorFactionId) {
    this.controllingMinorFactionId = controllingMinorFactionId;
    return this;
  }

   /**
   * Get controllingMinorFactionId
   * @return controllingMinorFactionId
  **/

  public String getControllingMinorFactionId() {
    return controllingMinorFactionId;
  }

  public void setControllingMinorFactionId(String controllingMinorFactionId) {
    this.controllingMinorFactionId = controllingMinorFactionId;
  }

  public EBGSSystemsV5 factions(List<EBGSFactionRefV5> factions) {
    this.factions = factions;
    return this;
  }

  public EBGSSystemsV5 addFactionsItem(EBGSFactionRefV5 factionsItem) {
    if (this.factions == null) {
      this.factions = new ArrayList<EBGSFactionRefV5>();
    }
    this.factions.add(factionsItem);
    return this;
  }

   /**
   * Get factions
   * @return factions
  **/

  public List<EBGSFactionRefV5> getFactions() {
    return factions;
  }

  public void setFactions(List<EBGSFactionRefV5> factions) {
    this.factions = factions;
  }

  public EBGSSystemsV5 conflicts(List<EBGSConflictSystemV5> conflicts) {
    this.conflicts = conflicts;
    return this;
  }

  public EBGSSystemsV5 addConflictsItem(EBGSConflictSystemV5 conflictsItem) {
    if (this.conflicts == null) {
      this.conflicts = new ArrayList<EBGSConflictSystemV5>();
    }
    this.conflicts.add(conflictsItem);
    return this;
  }

   /**
   * Get conflicts
   * @return conflicts
  **/

  public List<EBGSConflictSystemV5> getConflicts() {
    return conflicts;
  }

  public void setConflicts(List<EBGSConflictSystemV5> conflicts) {
    this.conflicts = conflicts;
  }

  public EBGSSystemsV5 factionHistory(List<EBGSFactionHistorySystemV5> factionHistory) {
    this.factionHistory = factionHistory;
    return this;
  }

  public EBGSSystemsV5 addFactionHistoryItem(EBGSFactionHistorySystemV5 factionHistoryItem) {
    if (this.factionHistory == null) {
      this.factionHistory = new ArrayList<EBGSFactionHistorySystemV5>();
    }
    this.factionHistory.add(factionHistoryItem);
    return this;
  }

   /**
   * Get factionHistory
   * @return factionHistory
  **/

  public List<EBGSFactionHistorySystemV5> getFactionHistory() {
    return factionHistory;
  }

  public void setFactionHistory(List<EBGSFactionHistorySystemV5> factionHistory) {
    this.factionHistory = factionHistory;
  }

  public EBGSSystemsV5 history(List<EBGSSystemHistoryV5> history) {
    this.history = history;
    return this;
  }

  public EBGSSystemsV5 addHistoryItem(EBGSSystemHistoryV5 historyItem) {
    if (this.history == null) {
      this.history = new ArrayList<EBGSSystemHistoryV5>();
    }
    this.history.add(historyItem);
    return this;
  }

   /**
   * Get history
   * @return history
  **/

  public List<EBGSSystemHistoryV5> getHistory() {
    return history;
  }

  public void setHistory(List<EBGSSystemHistoryV5> history) {
    this.history = history;
  }

  public EBGSSystemsV5 updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/

  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EBGSSystemsV5 ebGSSystemsV5 = (EBGSSystemsV5) o;
    return Objects.equals(this._id, ebGSSystemsV5._id) &&
        Objects.equals(this._v, ebGSSystemsV5._v) &&
        Objects.equals(this.eddbId, ebGSSystemsV5.eddbId) &&
        Objects.equals(this.name, ebGSSystemsV5.name) &&
        Objects.equals(this.nameLower, ebGSSystemsV5.nameLower) &&
        Objects.equals(this.nameAliases, ebGSSystemsV5.nameAliases) &&
        Objects.equals(this.x, ebGSSystemsV5.x) &&
        Objects.equals(this.y, ebGSSystemsV5.y) &&
        Objects.equals(this.z, ebGSSystemsV5.z) &&
        Objects.equals(this.systemAddress, ebGSSystemsV5.systemAddress) &&
        Objects.equals(this.population, ebGSSystemsV5.population) &&
        Objects.equals(this.government, ebGSSystemsV5.government) &&
        Objects.equals(this.allegiance, ebGSSystemsV5.allegiance) &&
        Objects.equals(this.state, ebGSSystemsV5.state) &&
        Objects.equals(this.security, ebGSSystemsV5.security) &&
        Objects.equals(this.primaryEconomy, ebGSSystemsV5.primaryEconomy) &&
        Objects.equals(this.secondaryEconomy, ebGSSystemsV5.secondaryEconomy) &&
        Objects.equals(this.needsPermit, ebGSSystemsV5.needsPermit) &&
        Objects.equals(this.reserveType, ebGSSystemsV5.reserveType) &&
        Objects.equals(this.controllingMinorFactionCased, ebGSSystemsV5.controllingMinorFactionCased) &&
        Objects.equals(this.controllingMinorFaction, ebGSSystemsV5.controllingMinorFaction) &&
        Objects.equals(this.controllingMinorFactionId, ebGSSystemsV5.controllingMinorFactionId) &&
        Objects.equals(this.factions, ebGSSystemsV5.factions) &&
        Objects.equals(this.conflicts, ebGSSystemsV5.conflicts) &&
        Objects.equals(this.factionHistory, ebGSSystemsV5.factionHistory) &&
        Objects.equals(this.history, ebGSSystemsV5.history) &&
        Objects.equals(this.updatedAt, ebGSSystemsV5.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, _v, eddbId, name, nameLower, nameAliases, x, y, z, systemAddress, population, government, allegiance, state, security, primaryEconomy, secondaryEconomy, needsPermit, reserveType, controllingMinorFactionCased, controllingMinorFaction, controllingMinorFactionId, factions, conflicts, factionHistory, history, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EBGSSystemsV5 {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    _v: ").append(toIndentedString(_v)).append("\n");
    sb.append("    eddbId: ").append(toIndentedString(eddbId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameLower: ").append(toIndentedString(nameLower)).append("\n");
    sb.append("    nameAliases: ").append(toIndentedString(nameAliases)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    z: ").append(toIndentedString(z)).append("\n");
    sb.append("    systemAddress: ").append(toIndentedString(systemAddress)).append("\n");
    sb.append("    population: ").append(toIndentedString(population)).append("\n");
    sb.append("    government: ").append(toIndentedString(government)).append("\n");
    sb.append("    allegiance: ").append(toIndentedString(allegiance)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    security: ").append(toIndentedString(security)).append("\n");
    sb.append("    primaryEconomy: ").append(toIndentedString(primaryEconomy)).append("\n");
    sb.append("    secondaryEconomy: ").append(toIndentedString(secondaryEconomy)).append("\n");
    sb.append("    needsPermit: ").append(toIndentedString(needsPermit)).append("\n");
    sb.append("    reserveType: ").append(toIndentedString(reserveType)).append("\n");
    sb.append("    controllingMinorFactionCased: ").append(toIndentedString(controllingMinorFactionCased)).append("\n");
    sb.append("    controllingMinorFaction: ").append(toIndentedString(controllingMinorFaction)).append("\n");
    sb.append("    controllingMinorFactionId: ").append(toIndentedString(controllingMinorFactionId)).append("\n");
    sb.append("    factions: ").append(toIndentedString(factions)).append("\n");
    sb.append("    conflicts: ").append(toIndentedString(conflicts)).append("\n");
    sb.append("    factionHistory: ").append(toIndentedString(factionHistory)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
