/*
 *    Copyright 2021 Frederic Thevenet
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * Elite BGS API
 * An API for Elite BGS
 *
 * OpenAPI spec version: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package eu.fthevenet.binjr.sources.adapters.elitebgs.api.v5;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EBGSSystemsPageV5
 */


public abstract class EBGSPageV5<T> {
  @SerializedName("docs")
  protected List<T> docs;

  @SerializedName("total")
  protected int total;

  @SerializedName("limit")
  protected int limit;

  @SerializedName("page")
  protected int page;

  @SerializedName("pages")
  protected int pages;

  public EBGSPageV5 docs(List<T> docs) {
    this.docs = docs;
    return this;
  }

  public EBGSPageV5 addDocsItem(T docsItem) {
    if (this.docs == null) {
      this.docs = new ArrayList<T>();
    }
    this.docs.add(docsItem);
    return this;
  }

   /**
   * Get docs
   * @return docs
  **/

  public List<T> getDocs() {
    return docs;
  }

  public void setDocs(List<T> docs) {
    this.docs = docs;
  }

  public EBGSPageV5 total(int total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/

  public int getTotal() {
    return total;
  }

  public void setTotal(int total) {
    this.total = total;
  }

  public EBGSPageV5 limit(int limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/

  public int getLimit() {
    return limit;
  }

  public void setLimit(int limit) {
    this.limit = limit;
  }

  public EBGSPageV5 page(int page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/

  public int getPage() {
    return page;
  }

  public void setPage(int page) {
    this.page = page;
  }

  public EBGSPageV5 pages(int pages) {
    this.pages = pages;
    return this;
  }

   /**
   * Get pages
   * @return pages
  **/

  public int getPages() {
    return pages;
  }

  public void setPages(int pages) {
    this.pages = pages;
  }

}
