/*
 *    Copyright 2021 Frederic Thevenet
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * Elite BGS API
 * An API for Elite BGS
 *
 * OpenAPI spec version: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package eu.fthevenet.binjr.sources.adapters.elitebgs.api.v5;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;
/**
 * EBGSConflictSystemV5
 */


public class EBGSConflictSystemV5 {
  @SerializedName("type")
  private String type;

  @SerializedName("status")
  private String status;

  @SerializedName("faction1")
  private EBGSConflictSystemFactionV5 faction1;

  @SerializedName("faction2")
  private EBGSConflictSystemFactionV5 faction2;

  public EBGSConflictSystemV5 type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public EBGSConflictSystemV5 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public EBGSConflictSystemV5 faction1(EBGSConflictSystemFactionV5 faction1) {
    this.faction1 = faction1;
    return this;
  }

   /**
   * Get faction1
   * @return faction1
  **/

  public EBGSConflictSystemFactionV5 getFaction1() {
    return faction1;
  }

  public void setFaction1(EBGSConflictSystemFactionV5 faction1) {
    this.faction1 = faction1;
  }

  public EBGSConflictSystemV5 faction2(EBGSConflictSystemFactionV5 faction2) {
    this.faction2 = faction2;
    return this;
  }

   /**
   * Get faction2
   * @return faction2
  **/

  public EBGSConflictSystemFactionV5 getFaction2() {
    return faction2;
  }

  public void setFaction2(EBGSConflictSystemFactionV5 faction2) {
    this.faction2 = faction2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EBGSConflictSystemV5 ebGSConflictSystemV5 = (EBGSConflictSystemV5) o;
    return Objects.equals(this.type, ebGSConflictSystemV5.type) &&
        Objects.equals(this.status, ebGSConflictSystemV5.status) &&
        Objects.equals(this.faction1, ebGSConflictSystemV5.faction1) &&
        Objects.equals(this.faction2, ebGSConflictSystemV5.faction2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, status, faction1, faction2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EBGSConflictSystemV5 {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    faction1: ").append(toIndentedString(faction1)).append("\n");
    sb.append("    faction2: ").append(toIndentedString(faction2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
