/*
 *    Copyright 2021 Frederic Thevenet
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * Elite BGS API
 * An API for Elite BGS
 *
 * OpenAPI spec version: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package eu.fthevenet.binjr.sources.adapters.elitebgs.api.v5;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;
/**
 * EBGSFactionRefV5
 */


public class EBGSFactionRefV5 {
  @SerializedName("faction_id")
  private String factionId;

  @SerializedName("name")
  private String name;

  @SerializedName("name_lower")
  private String nameLower;

  @SerializedName("faction_details")
  private EBGSFactionsV5 factionDetails;

  public EBGSFactionRefV5 factionId(String factionId) {
    this.factionId = factionId;
    return this;
  }

   /**
   * Get factionId
   * @return factionId
  **/

  public String getFactionId() {
    return factionId;
  }

  public void setFactionId(String factionId) {
    this.factionId = factionId;
  }

  public EBGSFactionRefV5 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EBGSFactionRefV5 nameLower(String nameLower) {
    this.nameLower = nameLower;
    return this;
  }

   /**
   * Get nameLower
   * @return nameLower
  **/

  public String getNameLower() {
    return nameLower;
  }

  public void setNameLower(String nameLower) {
    this.nameLower = nameLower;
  }

  public EBGSFactionRefV5 factionDetails(EBGSFactionsV5 factionDetails) {
    this.factionDetails = factionDetails;
    return this;
  }

   /**
   * Get factionDetails
   * @return factionDetails
  **/

  public EBGSFactionsV5 getFactionDetails() {
    return factionDetails;
  }

  public void setFactionDetails(EBGSFactionsV5 factionDetails) {
    this.factionDetails = factionDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EBGSFactionRefV5 ebGSFactionRefV5 = (EBGSFactionRefV5) o;
    return Objects.equals(this.factionId, ebGSFactionRefV5.factionId) &&
        Objects.equals(this.name, ebGSFactionRefV5.name) &&
        Objects.equals(this.nameLower, ebGSFactionRefV5.nameLower) &&
        Objects.equals(this.factionDetails, ebGSFactionRefV5.factionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(factionId, name, nameLower, factionDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EBGSFactionRefV5 {\n");
    
    sb.append("    factionId: ").append(toIndentedString(factionId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameLower: ").append(toIndentedString(nameLower)).append("\n");
    sb.append("    factionDetails: ").append(toIndentedString(factionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
