/*
 *    Copyright 2021 Frederic Thevenet
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * Elite BGS API
 * An API for Elite BGS
 *
 * OpenAPI spec version: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package eu.fthevenet.binjr.sources.adapters.elitebgs.api.v5;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * TickTimesV5
 */


public class TickTimesV5 {
  @SerializedName("_id")
  private String _id;

  @SerializedName("__v")
  private int _v;

  @SerializedName("last_tick")
  private String lastTick;

  @SerializedName("updated_at")
  private String updatedAt;

  @SerializedName("history")
  private List<TickTimesHistoryV5> history;

  public TickTimesV5 _id(String _id) {
    this._id = _id;
    return this;
  }

   /**
   * Get _id
   * @return _id
  **/

  public String getId() {
    return _id;
  }

  public void setId(String _id) {
    this._id = _id;
  }

  public TickTimesV5 _v(int _v) {
    this._v = _v;
    return this;
  }

   /**
   * Get _v
   * @return _v
  **/

  public int getV() {
    return _v;
  }

  public void setV(int _v) {
    this._v = _v;
  }

  public TickTimesV5 lastTick(String lastTick) {
    this.lastTick = lastTick;
    return this;
  }

   /**
   * Get lastTick
   * @return lastTick
  **/

  public String getLastTick() {
    return lastTick;
  }

  public void setLastTick(String lastTick) {
    this.lastTick = lastTick;
  }

  public TickTimesV5 updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/

  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public TickTimesV5 history(List<TickTimesHistoryV5> history) {
    this.history = history;
    return this;
  }

  public TickTimesV5 addHistoryItem(TickTimesHistoryV5 historyItem) {
    if (this.history == null) {
      this.history = new ArrayList<TickTimesHistoryV5>();
    }
    this.history.add(historyItem);
    return this;
  }

   /**
   * Get history
   * @return history
  **/

  public List<TickTimesHistoryV5> getHistory() {
    return history;
  }

  public void setHistory(List<TickTimesHistoryV5> history) {
    this.history = history;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TickTimesV5 tickTimesV5 = (TickTimesV5) o;
    return Objects.equals(this._id, tickTimesV5._id) &&
        Objects.equals(this._v, tickTimesV5._v) &&
        Objects.equals(this.lastTick, tickTimesV5.lastTick) &&
        Objects.equals(this.updatedAt, tickTimesV5.updatedAt) &&
        Objects.equals(this.history, tickTimesV5.history);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, _v, lastTick, updatedAt, history);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TickTimesV5 {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    _v: ").append(toIndentedString(_v)).append("\n");
    sb.append("    lastTick: ").append(toIndentedString(lastTick)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
